version: '3.1'

services:
  mysqldb:
    image: mysql:5.7
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password", "--explicit_defaults_for_timestamp"]
    environment:
      - MYSQL_ROOT_PASSWORD=password0123
      - MYSQL_DATABASE=clubhotelcusco_db
      - MYSQL_USER=clubhotelcusco
      - MYSQL_PASSWORD=951chcpwd753
    volumes:
      - ./docker_config/db/testdata.sql:/docker-entrypoint-initdb.d/testdata.sql

  flask-api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/home/app/clubhotelcusco_cotizaciones
